Support GHC 9.6.
The nix-shell breaks here, since it's using a snapshot too old to have
this LTS. I don't know how to fix it; when I put

    url = "https://github.com/input-output-hk/haskell.nix/archive/5559d7bc4ad00bada614d1c4473d5cf38eb905f2.tar.gz";
    sha256 = "1a9cbaq1h5wq9awijq98zkwaalbvqjql98zms2zgjbhxl3kg524m";

taken from excelsior's current master, I get another error:

    error: function 'anonymous lambda' called with unexpected argument 'fetchSubmodules'